// Code generated by "stringer -type=Status -linecomment -output=execution.string_gen.go"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CasePassed-0]
	_ = x[CaseFailed-1]
	_ = x[CaseRejected-2]
	_ = x[CaseRepeated-3]
	_ = x[CaseDiverged-4]
	_ = x[CaseRefused-5]
}

const _Status_name = "passedfailedrejectedrepeateddivergedrefused"

var _Status_index = [...]uint8{0, 6, 12, 20, 28, 36, 43}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
