// Code generated by "stringer -type=Relevance -linecomment -output=explain.string_gen.go"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Untested-0]
	_ = x[AnyValueFails-1]
	_ = x[ValueMatters-2]
}

const _Relevance_name = "untestedany-value-failsvalue-matters"

var _Relevance_index = [...]uint8{0, 8, 23, 36}

func (i Relevance) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Relevance_index)-1 {
		return "Relevance(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Relevance_name[_Relevance_index[idx]:_Relevance_index[idx+1]]
}
