// Code generated by "stringer -type=Outcome -linecomment -output=runner.string_gen.go"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Passed-0]
	_ = x[Counterexample-1]
	_ = x[Flaky-2]
	_ = x[Rejected-3]
	_ = x[CoverageUnmet-4]
	_ = x[Vacuous-5]
}

const _Outcome_name = "passedcounterexampleflakyrejectedcoverage-unmetvacuous"

var _Outcome_index = [...]uint8{0, 6, 20, 25, 33, 47, 54}

func (i Outcome) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Outcome_index)-1 {
		return "Outcome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Outcome_name[_Outcome_index[idx]:_Outcome_index[idx+1]]
}
