// Code generated by "stringer -type=Difference -linecomment -output=divergence.string_gen.go"; DO NOT EDIT.

package prop

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequestDifference-0]
	_ = x[FingerprintDifference-1]
	_ = x[VerdictDifference-2]
}

const _Difference_name = "requestfingerprintverdict"

var _Difference_index = [...]uint8{0, 7, 18, 25}

func (i Difference) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Difference_index)-1 {
		return "Difference(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Difference_name[_Difference_index[idx]:_Difference_index[idx+1]]
}
