// Code generated by "stringer -type=Part -linecomment -output=place.string_gen.go"; DO NOT EDIT.

package prop

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SwarmPart-0]
	_ = x[SetupPart-1]
	_ = x[SequentialPart-2]
	_ = x[ConcurrentPart-3]
	_ = x[DrainPart-4]
	_ = x[SettlePart-5]
}

const _Part_name = "swarmsetupsequentialconcurrentdrainsettle"

var _Part_index = [...]uint8{0, 5, 10, 20, 30, 35, 41}

func (i Part) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Part_index)-1 {
		return "Part(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Part_name[_Part_index[idx]:_Part_index[idx+1]]
}
