// Code generated by "stringer -type=Kind -linecomment -output=kind.string_gen.go"; DO NOT EDIT.

package choice

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Integer-0]
	_ = x[Float-1]
	_ = x[Sequence-2]
}

const _Kind_name = "integerfloatsequence"

var _Kind_index = [...]uint8{0, 7, 12, 20}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
