// Code generated by "stringer -type=NaNPolicy -linecomment -output=nanpolicy.string_gen.go"; DO NOT EDIT.

package choice

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExcludeNaN-0]
	_ = x[AdmitNaN-1]
}

const _NaNPolicy_name = "exclude-nanadmit-nan"

var _NaNPolicy_index = [...]uint8{0, 11, 20}

func (i NaNPolicy) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NaNPolicy_index)-1 {
		return "NaNPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NaNPolicy_name[_NaNPolicy_index[idx]:_NaNPolicy_index[idx+1]]
}
