// Code generated by "stringer -type=Width -linecomment -output=width.string_gen.go"; DO NOT EDIT.

package choice

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Width32-32]
	_ = x[Width64-64]
}

const (
	_Width_name_0 = "32"
	_Width_name_1 = "64"
)

func (i Width) String() string {
	switch {
	case i == 32:
		return _Width_name_0
	case i == 64:
		return _Width_name_1
	default:
		return "Width(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
