// Code generated by "stringer -type=Anomaly -linecomment -output=anomaly.string_gen.go"; DO NOT EDIT.

package history

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GarbageRead-1]
	_ = x[DuplicateAppend-2]
	_ = x[InternalInconsistency-3]
	_ = x[IncompatibleOrder-4]
	_ = x[AbortedRead-5]
	_ = x[IntermediateRead-6]
	_ = x[G0-7]
	_ = x[G1c-8]
	_ = x[GSingle-9]
	_ = x[GNonadjacent-10]
	_ = x[G2-11]
}

const _Anomaly_name = "garbage-readduplicate-appendinternal-inconsistencyincompatible-orderaborted-readintermediate-readG0G1cG-singleG-nonadjacentG2"

var _Anomaly_index = [...]uint8{0, 12, 28, 50, 68, 80, 97, 99, 102, 110, 123, 125}

func (i Anomaly) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Anomaly_index)-1 {
		return "Anomaly(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Anomaly_name[_Anomaly_index[idx]:_Anomaly_index[idx+1]]
}
