// Code generated by "stringer -type=Kind -linecomment -output=kind.string_gen.go"; DO NOT EDIT.

package history

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invoke-1]
	_ = x[OK-2]
	_ = x[Fail-3]
	_ = x[Unknown-4]
}

const _Kind_name = "invokeokfailunknown"

var _Kind_index = [...]uint8{0, 6, 8, 12, 19}

func (i Kind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
