// Code generated by "stringer -type=Limit -linecomment -output=limit.string_gen.go"; DO NOT EDIT.

package history

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LimitSteps-1]
	_ = x[LimitMemo-2]
	_ = x[LimitTime-3]
}

const _Limit_name = "stepsmemotime"

var _Limit_index = [...]uint8{0, 5, 9, 13}

func (i Limit) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Limit_index)-1 {
		return "Limit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Limit_name[_Limit_index[idx]:_Limit_index[idx+1]]
}
