// Code generated by "stringer -type=Relation -linecomment -output=relation.string_gen.go"; DO NOT EDIT.

package history

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WW-1]
	_ = x[WR-2]
	_ = x[RW-3]
}

const _Relation_name = "wwwrrw"

var _Relation_index = [...]uint8{0, 2, 4, 6}

func (i Relation) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Relation_index)-1 {
		return "Relation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Relation_name[_Relation_index[idx]:_Relation_index[idx+1]]
}
