// Code generated by "stringer -type=Verdict -linecomment -output=verdict.string_gen.go"; DO NOT EDIT.

package history

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Passed-0]
	_ = x[Violated-1]
	_ = x[Undecided-2]
}

const _Verdict_name = "passedviolatedundecided"

var _Verdict_index = [...]uint8{0, 6, 14, 23}

func (i Verdict) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Verdict_index)-1 {
		return "Verdict(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verdict_name[_Verdict_index[idx]:_Verdict_index[idx+1]]
}
